name: Check Builds

on:
  push:
    paths:
        - lib/**
        - bot/**
        - cnc/**
        - shell/**
        - tools/**
        - cmake-modules/**
        - .github/workflows/check-build.yaml
        - CMakeLists.txt

jobs:
  ubuntu-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Install dependencies
        run: sudo apt install clang cmake -y
      - name: Create CMake build files
        run: cmake -B build
      - name: Check compilation
        run: cmake --build build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: laika-demo-binaries-ubuntu
          path: bin

  windows-build:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create CMake build files
        run: cmake -B build
      - name: Check compilation
        run: cmake --build build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: laika-demo-binaries-windows
          path: bin

  macOS-build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Create CMake build files
        run: cmake -B build
      - name: Check compilation
        run: cmake --build build
      - name: Upload build artifact
        uses: actions/upload-artifact@v2
        with:
          name: laika-demo-binaries-macos
          path: bin